"""empty message

Revision ID: 556b3f66e18d
Revises: 93933fe41648
Create Date: 2022-08-14 15:20:04.937957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556b3f66e18d'
down_revision = '93933fe41648'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
