"""empty message

Revision ID: 5f1aeeda5fa1
Revises: 556b3f66e18d
Create Date: 2022-08-14 15:20:31.869377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f1aeeda5fa1'
down_revision = '556b3f66e18d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
